// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiNet.Data;

#nullable disable

namespace WebApiNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225102254_ClienteToNormality")]
    partial class ClienteToNormality
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApiNet.Models.Alquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteDni")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("FechaAlquiler")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaDevolucion")
                        .HasColumnType("date");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("VehiculoMatricula")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteDni");

                    b.HasIndex("VehiculoMatricula");

                    b.ToTable("Alquileres");
                });

            modelBuilder.Entity("WebApiNet.Models.Cliente", b =>
                {
                    b.Property<string>("Dni")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Dni");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("WebApiNet.Models.Vehiculos", b =>
                {
                    b.Property<string>("Matricula")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<double>("LitrosTanque")
                        .HasColumnType("double");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TipoVehiculo")
                        .HasColumnType("int");

                    b.HasKey("Matricula");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("WebApiNet.Models.Alquiler", b =>
                {
                    b.HasOne("WebApiNet.Models.Cliente", "Cliente")
                        .WithMany("Alquileres")
                        .HasForeignKey("ClienteDni")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiNet.Models.Vehiculos", "Vehiculo")
                        .WithMany("Alquileres")
                        .HasForeignKey("VehiculoMatricula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("WebApiNet.Models.Cliente", b =>
                {
                    b.Navigation("Alquileres");
                });

            modelBuilder.Entity("WebApiNet.Models.Vehiculos", b =>
                {
                    b.Navigation("Alquileres");
                });
#pragma warning restore 612, 618
        }
    }
}
